version: '2'
services:
  ticket:
    build: .
    container_name: flaguesser-ticket
    command: npm run dev
    restart: always
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    links:
      - "ticketdb:postgres"
    environment:
      DB_PASSWORD: "password"
      DB_USER: "postgres"
      DB_HOST: "postgres"
      DB_PORT: "5432"
      DB_NAME: "ticket"
  ticketdb:
    container_name: flaguesser-ticketdb
    image: postgres:9.6.2-alpine
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: "ticket"
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "postgres"
    restart: always
    volumes:
      - ticket-volume:/var/lib/postgresql/data

volumes:
  player-volume:
  match-volume:
  ticket-volume: